
Discord.Lang = {
    ONLINE_MESSAGE_TITLE = 'Сервер запущен',
    ONLINE_MESSAGE_DESCRIPTION = 'Можно подключаться по IP <join_url>!',
    PLAYER_JOIN = 'Игрок <name> (<steam_id>) заходит на сервер',
    PLAYER_DISCONNECT = 'Игрок <name> (<steam_id>) вышел (<reason>)',
    CHECK_DISCORD = 'Проверь свой статус игры в дискорде.',
    RPC_ABORTED = 'Запрос отклонён.',
    SOMETHING_WENT_WRONG = 'Ой. Что-то поломалось, проверьте консоль.',
    DISCORD_NOT_FOUND = 'У вас не установлен модуль gdiscord.',
    JOINED_DISCORD = '',
    JOINED_DISCORD_ALREADY = '',
    ACCOUNT_LINKED = '',
    CONNECTIONS_NOT_FOUND = '',
    SYNCED_RANK_DISCORD = '',
    NONEXISTANT_ROLE = '',
    NOT_CONFIGURED_FOR_USERGROUP = '',
    NO_LINKED_ACCOUNTS = '',
    RATELIMITED = 'Подождите.',
    INTERNAL_SERVER_ERROR = 'Ошибка с серверной стороны. подождите.',
    NO_STEAM_CONNECTIONS = '',
    SYNCED_USERGROUP_GMOD = '',
    CENTER_TEXT = '',
    CENTER_BELOW_TEXT = '',
    JOIN_BUTTON = 'Да',
    LATER_BUTTON = 'Нет',
    JOIN_REWARDS_NOT_CONFIGURED = 'Join Rewards is not configured properly on the server. Report to the server owner.',
    COULDNT_RETRIEVE_TOKEN_DATA = 'Couldn\'t retrieve token data from Discord. Try again later.',
    ACCESS_TOKEN_HAS_NO_REQUIRED_PERMS = 'Access token has no required permission.',
    COULDNT_RETRIEVE_USER_DATA = 'Couldn\'t retrieve user data from Discord. Try again later.',
    COULDNT_MAKE_YOU_JOIN = 'Couldn\'t make you join the discord. Try again later.',
    SOMETHING_WENT_WRONG_CHECKING_PREVIOUS_JOIN_DATA = 'Something went wrong while trying to check for previous joins into the discord. Try again later.',
    SOMETHING_WENT_WRONG_CONFIRMING_JOIN = 'Something went wrong while trying to confirm your joining into the discord. Try again later.',
    RANK_SYNC_NOT_CONFIGURED = 'Rank Sync is not configured properly on the server. Report to the server owner.',
    INTERNAL_ERROR_WHILE_LINKING_ACCOUNT = 'Internal error happened while trying to link your account, try again later.',
    COMMAND_EVENT = 'Запущена команда',
    COMMAND_ERROR = 'Лог ошибки команды',
    NO_PERMISSIONS = 'У вас нет доступа к этой команде.',
    IP = 'IP',
    GAMEMODE = 'Режим',
    MAP = 'Карта',
    PLAYERS = 'Игроки',
    STAFF_ONLINE = 'Администрация',
    NO_ARGUMENT_PROVIDED = 'Отсутствует аргумент.',
    PLAYER_COULDNT_BE_FOUND = 'Игрок не найден.',
    SAID_AS_CONSOLE = 'Сказал ``<cmd>`` как консоль в чат.',
    RAN_IN_CONSOLE = 'Запустил ``<cmd>`` в консоль.',
    RAN_CODE_ON_SERVER = 'Код запущен:\n```lua\n<cmd>\n```',
    KICKED_PLAYER_WITH_REASON = 'Игрок "<name>" был кикнут с причиной "<reason>".',
    KICKED_PLAYER = 'Игрок "<name>". Был кикнут.',
    FAILED_SCREENSHOTTING = 'Ошибка скриншота "<name>": <err>',
    SCREENSHOT_OF_PLAYER = 'Скриншот игрока "<name>" (<sid64>)',
    HELP_TITLE = 'Discord Integration - Help',
    HELP_DESCRIPTION = [[status - Информация о сервере
rcon <STRING> - Запустить код на серверной части в консоли
lua <STRING> - Запустить код на серверной части
kick <PLAYER> - Кикнуть игрока
ss <PLAYER> - Взять скриншот с игрока]],
    INVALID_PLAYER = 'Игрок не найден.',
    ALREADY_BEING_SCREENSHOTTED = 'Экран этого игрока уже захватывается.',
    ULX_TITLE = 'Лог действий через ULX',
}