AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
include("shared.lua")

util.AddNetworkString("Ability_ClientsideCooldown")
util.AddNetworkString("SHAKY_SetForcedAnimSync")
util.AddNetworkString("SHAKY_EndForcedAnimSync")
util.AddNetworkString("GestureClientNetworking")
util.AddNetworkString("ForbidTalant")
util.AddNetworkString("ThirdPersonCutscene")